### ISSUE TITLE
Timing accuracy option

### ISSUE THREAD

**Issue by atdr** [okofish/qlab-html#1]
A flag to output cue timings to 3 decimal places (milliseconds) would be helpful.

> The pre-wait, action, and post-wait columns display seconds with two decimal places, but QLab is actually accurate to three decimal places.
> — [QLab docs](http://figure53.com/docs/qlab/v4/general/getting-started/#notes-about-pre-wait-action-and-post-wait)

**Comment by okofish** [comment]
That's a good idea, thanks! I've added the --ms option.
