### ISSUE TITLE
Compiled version? 

### ISSUE THREAD

**Issue by SteadyStatus21** [okofish/qlab-html#2]
Hello.
I am wondering if you have a complied version?
I do not have the time to download xcode and install node and nodejs.

Thanks,
Alex

**Comment by okofish** [comment]
No, I do not have a compiled version. (JavaScript is, generally speaking, an interpreted language.)

I’m not sure off the top of my head why you would need Xcode, unless it’s a macOS dependency of Node.js that I wasn’t   consciously aware of.
